In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torchvision

In [2]:
train_data = torchvision.datasets.MNIST(
    root = 'data',
    train = True,                         
    transform = torchvision.transforms.ToTensor(), 
    download = True,            
)
test_data = torchvision.datasets.MNIST(
    root = 'data', 
    train = False, 
    transform = torchvision.transforms.ToTensor()
)

In [3]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [4]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [64]:
X = torch.flatten(test_data.data,start_dim=1).float()
y = test_data.targets

In [73]:
dimension_input = 784
dimension_h = [128, 64]
dimension_output = 10
model = torch.nn.Sequential(
    torch.nn.Linear(784,dimension_h[0]),
    torch.nn.ReLU(),
    
    torch.nn.Linear(dimension_h[0],dimension_h[1]),
    torch.nn.ReLU(),
    
    torch.nn.Linear(dimension_h[1],10),
    torch.nn.Softmax(dim=1)
)

In [74]:
learning_rate = 0.001
critterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [75]:
for epoch in range(3000):
    y_pred = model(X)
    loss = critterion(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if(epoch%1000==0):
        print(epoch, loss.item())

0 2.315244436264038
1000 1.4692717790603638
2000 1.467957854270935


In [76]:
model(X)

tensor([[5.0561e-20, 5.7230e-36, 1.8654e-23,  ..., 1.0000e+00, 1.4783e-25,
         4.6638e-26],
        [9.1255e-29, 9.3986e-27, 1.0000e+00,  ..., 0.0000e+00, 2.2743e-30,
         0.0000e+00],
        [4.5725e-22, 1.0000e+00, 3.8861e-18,  ..., 3.9714e-13, 7.2150e-26,
         2.3256e-21],
        ...,
        [8.9419e-24, 2.3864e-23, 6.9509e-28,  ..., 7.0779e-15, 1.9056e-18,
         7.6785e-14],
        [2.5856e-39, 6.6598e-38, 0.0000e+00,  ..., 1.0042e-36, 1.1476e-36,
         2.8026e-45],
        [4.0806e-32, 0.0000e+00, 0.0000e+00,  ..., 2.2369e-31, 1.0411e-37,
         0.0000e+00]], grad_fn=<SoftmaxBackward0>)

In [77]:
max_of_model = y_pred.max(1)[1]
print(max_of_model)

tensor([7, 2, 1,  ..., 4, 5, 6])


In [78]:
test_data.targets

tensor([7, 2, 1,  ..., 4, 5, 6])

In [79]:
corrects = ( max_of_model == y)
accuracy = corrects.sum().float() / float( y.size(0) )
accuracy

tensor(0.9932)